version: "3.8"

services:
  bdg-app:
    build: ./
    ports:
      - 80:80
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: bdg-tech-test

  bdg-mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./bdg-tech-test-data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bdg-tech-test
